project:
  type: book

book:
  title: "CodebookRepository_BrookeSarah"
  author: "Jane Doe"
  date: "4/19/2023"
  chapters:
    - index.qmd
    - Chapter1.qmd
    - Chapter2.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

